---
title: "Vietnam serum bank"
number-sections: true
format:
  html:
    toc: true
    toc-depth: 4
editor: source
editor_options: 
  chunk_output_type: console
#bibliography: references.bib
#csl: the-american-naturalist.csl
---

```{r include = FALSE, eval = FALSE}
# The code that adds the .nojekyll file to the GitHub repository:
file <- ".nojekyll"
file.create(file)
gert::git_add(file)
gert::git_commit("Adding the .nojekyll file")
gert::git_push()
rm(file)
```

```{r include = FALSE, eval = FALSE}
run_all <- function() {
  knitr::purl("index.qmd", "tmp.R", documentation = FALSE)
  source("tmp.R")
  file.remove("tmp.R")  
}

rerun_all <- function() {
  rm(list  = grep("run_all", ls(envir = .GlobalEnv), value = TRUE, invert = TRUE),
     envir = .GlobalEnv)
  run_all()
}
```

```{r include = FALSE}
par2 <- function(...) par(..., mgp = c(1.5, .5, 0), bty = "n")

knitr::knit_hooks$set(
  margin1 = function(before, options, envir) {
    if (before) par2(plt = c(.105, .97, .15, .95)) else NULL
  })

eps <- .8
knitr::opts_chunk$set(margin1    = TRUE,
                      fig.retina = 2,
                      fig.align  = "center",
                      fig.height = eps * 5, # default is 5
                      fig.width  = eps * 7) # default is 7 and maximum possible is 8.3
```


## Contants

The OneDrive root:

```{r}
OneDrive <- "~/Library/CloudStorage/OneDrive-OxfordUniversityClinicalResearchUnit"
```

Path to raw data:

```{r}
path2data <- paste0(OneDrive, "/SPECIAL/MODELLING/Hoang Nhung/20FL/20FL_samples/",
                    "20FL_samples_v2/standardized_20FL_metadata/")
```

```{r include = FALSE}
path2cache <- paste0(stringr::str_replace(getwd(), Sys.getenv("HOME"), OneDrive),
                     "/cache/")
if (! dir.exists(path2cache)) dir.create(path2cache)
make_path <- function(x) paste0(path2cache, x)
file_exists <- function(x) file.exists(make_path(x))
readRDScache <- function(x) readRDS(make_path(x))
saveRDScache <- function(object, file) saveRDS(object, make_path(file))
```


## Packages

Required packages:

```{r}
required <- c("readxl", "stringr", "purrr", "dplyr")
```

Installing those that are not installed yet:

```{r}
to_install <- required[! required %in% installed.packages()[,"Package"]]
if (length(to_install)) install.packages(to_install)
```

Loading the packages for interactive use:

```{r warning = FALSE, message = FALSE}
invisible(sapply(required, library, character.only = TRUE))
```

## Functions

```{r}
set_names2 <- function(x) {
  setNames(x, x |>
             str_remove("^.*/") |> 
             str_remove(".xlsx$"))
}
```

## Reading the data

Takes 3.5":

```{r eval = FALSE}
dataset <- path2data |>
  list.files(".xlsx$", full.names = TRUE, recursive = TRUE) |> 
  grep("~", x = _, value = TRUE, invert = TRUE) |> 
  map(read_excel) |> 
  bind_rows()
```

```{r include = FALSE}
if (file_exists("dataset.rds")) {
  dataset <- readRDScache("dataset.rds")
} else {
  dataset <- path2data |>
    list.files(".xlsx$", full.names = TRUE, recursive = TRUE) |> 
    grep("~", x = _, value = TRUE, invert = TRUE) |> 
    map(read_excel) |>
    bind_rows()
  saveRDScache(dataset, "dataset.rds")
}
```

